apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: brcroner/kube-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              value: 'auth-service.default'
            - name: ZIPKIN_COLLECTOR_SERVICE_HOST
              value: '192.168.1.83'
            - name: ZIPKIN_COLLECTOR_SERVICE_PORT
              value: '9411'
